// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_imgButton4(lv_event_t * e);
void ui_event_imgButton5(lv_event_t * e);
void ui_event_imgButton6(lv_event_t * e);
void ui_event_imgButton7(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
