// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_event_imgButton4(lv_event_t * e)
{
	// Your code here
}

void ui_event_imgButton5(lv_event_t * e)
{
	// Your code here
}

void ui_event_imgButton6(lv_event_t * e)
{
	// Your code here
}

void ui_event_imgButton7(lv_event_t * e)
{
	// Your code here
}
