// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
lv_obj_t * ui_ImgButton7 = NULL;
// event funtions
// 全局变量：记录全屏控件（避免重复创建）
static lv_obj_t *fullscreen_img = NULL;
static lv_obj_t *fullscreen_mask = NULL;

// 滑动相关全局变量
static int current_pic_index = 101;           // 当前显示的图片编号
static int total_pics = 104;                  // 总图片数量
static int touch_start_x = 0;               // 触摸开始X坐标
static int touch_start_y = 0;               // 触摸开始Y坐标
static int touch_end_x = 0;                 // 触摸结束X坐标
static int touch_end_y = 0;                 // 触摸结束Y坐标
static int touching = 0;                    // 是否正在触摸

// 退出全屏的回调函数
static void close_fullscreen_event(lv_event_t *e) {
    // 销毁全屏控件
    if(fullscreen_img) lv_obj_del(fullscreen_img);
    if(fullscreen_mask) lv_obj_del(fullscreen_mask);
    fullscreen_img = NULL;
    fullscreen_mask = NULL;

    // 重置触摸状态
    touch_start_x = 0;
    touch_start_y = 0;
    touch_end_x = 0;
    touch_end_y = 0;
    touching = 0;
}

// 更新全屏图片
static void update_fullscreen_image() {
    if(fullscreen_img) {
        char img_path[50];
        sprintf(img_path, "S:/mydata/%d.bmp", current_pic_index);
        lv_img_set_src(fullscreen_img, img_path);
    }
}

// 全屏模式的触摸事件处理
static void fullscreen_touch_event(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_indev_t *indev = lv_event_get_indev(e);
    lv_point_t point;
    
    if(event_code == LV_EVENT_PRESSED) {
        // 手指按下
        lv_indev_get_point(indev, &point);
        touch_start_x = point.x;
        touch_start_y = point.y;
        touch_end_x = point.x;
        touch_end_y = point.y;
        touching = 1;
        printf("触摸开始: (%d, %d)\n", touch_start_x, touch_start_y);
    }
    else if(event_code == LV_EVENT_RELEASED) {
        // 手指抬起
        if(touching) {
            lv_indev_get_point(indev, &point);
            touch_end_x = point.x;
            touch_end_y = point.y;
            touching = 0;
            printf("触摸结束: (%d, %d)\n", touch_end_x, touch_end_y);
            
            // 计算滑动距离
            int delta_x = touch_start_x - touch_end_x;
            int abs_delta_x = delta_x > 0 ? delta_x : -delta_x;
            
            // 判断滑动距离是否大于阈值（这里使用50像素作为阈值）
            if(abs_delta_x > 50) {
                if(delta_x > 0) {
                    // 向左滑动（从右向左）
                    current_pic_index++;
                    if(current_pic_index > total_pics) {
                        current_pic_index = 101;
                    }
                    printf("向左滑动，切换到图片 %d\n", current_pic_index);
                }
                else {
                    // 向右滑动（从左向右）
                    current_pic_index--;
                    if(current_pic_index < 101) {
                        current_pic_index = total_pics;
                    }
                    printf("向右滑动，切换到图片 %d\n", current_pic_index);
                }
                
                // 更新全屏图片
                update_fullscreen_image();
            }
            else {
                // 滑动距离不足，视为点击，退出全屏
                printf("滑动距离(%d)不足，退出全屏\n", abs_delta_x);
                close_fullscreen_event(e);
            }
            
            // 重置触摸坐标
            touch_start_x = touch_start_y = touch_end_x = touch_end_y = 0;
        }
    }
    else if(event_code == LV_EVENT_PRESSING) {
        // 手指正在按压（移动中）
        if(touching) {
            lv_indev_get_point(indev, &point);
            touch_end_x = point.x;
            touch_end_y = point.y;
        }
    }
}

static void show_fullscreen_image(int pic_index){
    // 设置当前图片索引
    current_pic_index = pic_index;
    
    // 1. 创建全屏遮罩层（黑色半透明，点击可退出）
    fullscreen_mask = lv_obj_create(lv_scr_act());
    lv_obj_set_size(fullscreen_mask, lv_disp_get_hor_res(NULL), lv_disp_get_ver_res(NULL));
    lv_obj_set_style_bg_color(fullscreen_mask, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(fullscreen_mask, 200, 0); // 半透明
    lv_obj_center(fullscreen_mask); // 居中显示
    // 为遮罩层添加触摸事件（处理滑动和点击）
    lv_obj_add_event_cb(fullscreen_mask, fullscreen_touch_event, LV_EVENT_ALL, NULL);

    // 2. 创建全屏图片控件
    fullscreen_img = lv_img_create(fullscreen_mask);
    
    // 根据索引设置图片路径
    char img_path[50];
    sprintf(img_path, "S:/mydata/%d.bmp", current_pic_index);
    lv_img_set_src(fullscreen_img, img_path);
    
    // 3. 设置图片为全屏显示（与屏幕分辨率一致）
    lv_obj_set_size(fullscreen_img, lv_disp_get_hor_res(NULL), lv_disp_get_ver_res(NULL));
    lv_obj_center(fullscreen_img); // 居中显示

    // 5. 点击图片也能退出全屏
    lv_obj_add_event_cb(fullscreen_img, close_fullscreen_event, LV_EVENT_CLICKED, NULL);
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_screen2_screen_init);
    }
}

void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_fullscreen_image(101);
    }
}

void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_fullscreen_image(102);
    }
}

void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_fullscreen_image(103);
    }
}

void ui_event_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_fullscreen_image(104);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 333);
    lv_obj_set_y(ui_Button5, -200);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "菜单");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Chinese1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton4 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1_png, NULL);
    lv_obj_set_width(ui_ImgButton4, 160);
    lv_obj_set_height(ui_ImgButton4, 105);
    lv_obj_set_x(ui_ImgButton4, -300);
    lv_obj_set_y(ui_ImgButton4, -30);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    ui_ImgButton5 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2_png, NULL);
    lv_obj_set_width(ui_ImgButton5, 160);
    lv_obj_set_height(ui_ImgButton5, 105);
    lv_obj_set_x(ui_ImgButton5, -121);
    lv_obj_set_y(ui_ImgButton5, -29);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    ui_ImgButton6 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_3_png, NULL);
    lv_obj_set_width(ui_ImgButton6, 160);
    lv_obj_set_height(ui_ImgButton6, 105);
    lv_obj_set_x(ui_ImgButton6, 56);
    lv_obj_set_y(ui_ImgButton6, -31);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    ui_ImgButton7 = lv_imgbtn_create(ui_Screen4);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_4_png, NULL);
    lv_obj_set_width(ui_ImgButton7, 160);
    lv_obj_set_height(ui_ImgButton7, 105);
    lv_obj_set_x(ui_ImgButton7, 235);
    lv_obj_set_y(ui_ImgButton7, -30);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton7, ui_event_ImgButton7, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Button5 = NULL;
    ui_Label5 = NULL;
    ui_ImgButton4 = NULL;
    ui_ImgButton5 = NULL;
    ui_ImgButton6 = NULL;
    ui_ImgButton7 = NULL;

}
