// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <signal.h>
#include <string.h>

// 开发板中存在的音乐文件
const char *music_files[] = {
    "/mydata/mygo.mp3",
    "/mydata/csmp.mp3",
    NULL
};

static pid_t music_pid = 0;
static int current_idx = 0;
static int is_paused = 0;
static lv_timer_t *progress_timer = NULL;  // 进度计时器
static int current_progress = 0;           // 当前进度（0-100）

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_PlayPauseBtn = NULL;
lv_obj_t * ui_NextBtn = NULL;
lv_obj_t * ui_PrevBtn = NULL;
lv_obj_t * ui_CurrMusicLabel = NULL;
lv_obj_t * ui_ProgressBar = NULL;  // 进度条

// 函数声明（解决编译错误的关键：在使用前声明静态函数）
static void next_music(void);
static void play_music(int idx);

// 检查文件是否存在
static int file_exists(const char *path) {
    return access(path, F_OK) == 0;
}

// 停止音乐播放
static void stop_music(void) {
    if (music_pid > 0) {
        kill(music_pid, SIGKILL);
        waitpid(music_pid, NULL, 0);
        music_pid = 0;
        is_paused = 0;
    }
    // 停止进度计时器
    if (progress_timer != NULL) {
        lv_timer_del(progress_timer);
        progress_timer = NULL;
    }
    current_progress = 0;
    lv_bar_set_value(ui_ProgressBar, current_progress, LV_ANIM_ON);
}

// 进度条更新回调函数
static void progress_timer_cb(lv_timer_t *t) {
    if (is_paused) return;  // 暂停时不更新进度
    
    // 模拟进度更新
    current_progress += 1;
    if (current_progress >= 100) {
        current_progress = 0;
        next_music();  // 现在这里的调用会找到提前声明的函数
    }
    lv_bar_set_value(ui_ProgressBar, current_progress, LV_ANIM_ON);
}

// 播放指定索引的音乐
static void play_music(int idx) {
    if (idx < 0 || music_files[idx] == NULL) return;
    if (!file_exists(music_files[idx])) return;

    stop_music();
    current_idx = idx;
    current_progress = 0;
    lv_bar_set_value(ui_ProgressBar, current_progress, LV_ANIM_ON);

    pid_t pid = fork();
    if (pid == 0) {
        execlp("mplayer", "mplayer", "-quiet", music_files[idx], (char*)NULL);
        _exit(1);
    } else if (pid > 0) {
        music_pid = pid;
        is_paused = 0;
        // 创建进度计时器（1秒更新一次）
        progress_timer = lv_timer_create(progress_timer_cb, 1000, NULL);
    }
    // 更新显示
    lv_label_set_text(ui_CurrMusicLabel, strrchr(music_files[idx], '/') + 1);
    lv_label_set_text(lv_obj_get_child(ui_PlayPauseBtn, 0), "暂停");
}

// 切换播放/暂停状态
static void toggle_play_pause(void) {
    if (music_pid == 0) {
        play_music(current_idx);
        return;
    }

    if (is_paused) {
        kill(music_pid, SIGCONT);
        is_paused = 0;
        lv_label_set_text(lv_obj_get_child(ui_PlayPauseBtn, 0), "暂停");
    } else {
        kill(music_pid, SIGSTOP);
        is_paused = 1;
        lv_label_set_text(lv_obj_get_child(ui_PlayPauseBtn, 0), "播放");
    }
}

// 下一首
static void next_music(void) {
    int next_idx = current_idx + 1;
    if (music_files[next_idx] == NULL) next_idx = 0;
    play_music(next_idx);
}

// 上一首
static void prev_music(void) {
    int prev_idx = current_idx - 1;
    if (prev_idx < 0) {
        prev_idx = 0;
        while (music_files[prev_idx + 1] != NULL) prev_idx++;
    }
    play_music(prev_idx);
}

// 菜单按钮事件
void ui_event_Button4(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        stop_music();  // 返回菜单时停止播放
        _ui_screen_change(&ui_screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_screen2_screen_init);
    }
}

// 播放/暂停按钮事件
static void ui_event_PlayPauseBtn(lv_event_t * e) {
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        toggle_play_pause();
    }
}

// 下一首按钮事件
static void ui_event_NextBtn(lv_event_t * e) {
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        next_music();
    }
}

// 上一首按钮事件
static void ui_event_PrevBtn(lv_event_t * e) {
    if (lv_event_get_code(e) == LV_EVENT_CLICKED) {
        prev_music();
    }
}

// 页面初始化
void ui_Screen6_screen_init(void) {
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x000000), LV_PART_MAIN);  // 黑色背景

    // 菜单按钮
    ui_Button4 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 333);
    lv_obj_set_y(ui_Button4, -200);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);

    ui_Label4 = lv_label_create(ui_Button4);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "菜单");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Chinese1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 当前音乐显示标签
    ui_CurrMusicLabel = lv_label_create(ui_Screen6);
    lv_obj_set_align(ui_CurrMusicLabel, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_CurrMusicLabel, -50);
    lv_label_set_text(ui_CurrMusicLabel, strrchr(music_files[0], '/') + 1);
    lv_obj_set_style_text_color(ui_CurrMusicLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_CurrMusicLabel, &ui_font_Chinese1, LV_PART_MAIN);

    // 进度条
    ui_ProgressBar = lv_bar_create(ui_Screen6);
    lv_obj_set_width(ui_ProgressBar, 400);
    lv_obj_set_height(ui_ProgressBar, 20);
    lv_obj_set_align(ui_ProgressBar, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_ProgressBar, 0);
    lv_bar_set_range(ui_ProgressBar, 0, 100);
    lv_bar_set_value(ui_ProgressBar, 0, LV_ANIM_OFF);
    lv_obj_set_style_bg_color(ui_ProgressBar, lv_color_hex(0x333333), LV_PART_MAIN);  // 进度条背景
    lv_obj_set_style_bg_color(ui_ProgressBar, lv_color_hex(0x00FFFF), LV_PART_INDICATOR);  // 进度指示

    // 上一首按钮
    ui_PrevBtn = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_PrevBtn, 100);
    lv_obj_set_height(ui_PrevBtn, 50);
    lv_obj_set_x(ui_PrevBtn, -150);
    lv_obj_set_y(ui_PrevBtn, 50);
    lv_obj_set_align(ui_PrevBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrevBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_PrevBtn, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *prev_label = lv_label_create(ui_PrevBtn);
    lv_obj_set_align(prev_label, LV_ALIGN_CENTER);
    lv_label_set_text(prev_label, "上一首");
    lv_obj_set_style_text_font(prev_label, &ui_font_Chinese1, LV_PART_MAIN);

    // 播放/暂停按钮
    ui_PlayPauseBtn = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_PlayPauseBtn, 100);
    lv_obj_set_height(ui_PlayPauseBtn, 50);
    lv_obj_set_y(ui_PlayPauseBtn, 50);
    lv_obj_set_align(ui_PlayPauseBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlayPauseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_PlayPauseBtn, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *play_label = lv_label_create(ui_PlayPauseBtn);
    lv_obj_set_align(play_label, LV_ALIGN_CENTER);
    lv_label_set_text(play_label, "播放");
    lv_obj_set_style_text_font(play_label, &ui_font_Chinese1, LV_PART_MAIN);

    // 下一首按钮
    ui_NextBtn = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_NextBtn, 100);
    lv_obj_set_height(ui_NextBtn, 50);
    lv_obj_set_x(ui_NextBtn, 150);
    lv_obj_set_y(ui_NextBtn, 50);
    lv_obj_set_align(ui_NextBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NextBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_NextBtn, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *next_label = lv_label_create(ui_NextBtn);
    lv_obj_set_align(next_label, LV_ALIGN_CENTER);
    lv_label_set_text(next_label, "下一首");
    lv_obj_set_style_text_font(next_label, &ui_font_Chinese1, LV_PART_MAIN);

    // 绑定事件
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayPauseBtn, ui_event_PlayPauseBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextBtn, ui_event_NextBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrevBtn, ui_event_PrevBtn, LV_EVENT_ALL, NULL);
}

// 页面销毁
void ui_Screen6_screen_destroy(void) {
    stop_music();  // 销毁页面时停止播放
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // 重置指针
    ui_Screen6 = NULL;
    ui_Button4 = NULL;
    ui_Label4 = NULL;
    ui_PlayPauseBtn = NULL;
    ui_NextBtn = NULL;
    ui_PrevBtn = NULL;
    ui_CurrMusicLabel = NULL;
    ui_ProgressBar = NULL;
    progress_timer = NULL;
}