// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

// 新增：幻灯片图片控件（LVGL管理，避免fb0冲突）
extern lv_obj_t * ui_slide_img;
// 控制函数
extern void start_slide_show(void);
extern void stop_slide_show(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

