// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
extern void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
extern void ui_event_ImgButton7(lv_event_t * e);
extern lv_obj_t * ui_ImgButton7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

