// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen6;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
// 新增UI元素声明
extern lv_obj_t * ui_PlayPauseBtn;
extern lv_obj_t * ui_NextBtn;
extern lv_obj_t * ui_PrevBtn;
extern lv_obj_t * ui_CurrMusicLabel;
extern lv_obj_t * ui_ProgressBar;  // 进度条声明

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif